#
#
#

- name: add repositories and update
  include: apt.yml
  when: generic_manage_apt
  tags: apt

- name: installing unattended upgrades
  include: unattended-upgrades.yml
  when: generic_manage_unattended_upgrade
  tags: apt

- name: add ldap config
  include: add_ldap.yml
  when: use_ldap
  tags: ldap

- name: add SMTP smarthost
  include: smtp.yml
  when: generic_manage_smtp
  tags: smtp
