- debug: msg="config smtp"


- name: update exim4 base config file
  template:
    src: update_exim4.conf.conf.j2
    dest: /etc/exim4/update-exim4.conf.conf
    mode: 0644
    owner: root
    group: root

- name: update mailname
  template:
    src: mailname.j2
    dest: /etc/mailname
    mode: 0644
    owner: root
    group: root
