- name: update sshd config file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  register: sshd_config_update

- name: check config
  command: /usr/sbin/sshd -t
  when: sshd_config_update.changed
  register: sshd_config_check
  notify: restart sshd
