- name: restart nslcd
  service: name=nslcd state=restarted

- name: restart nscd
  service: name=nscd state=restarted

- name: reload exim4
  service: name=exim4 state=reloaded

- name: reapply iptables
  service: name=iptables state=reloaded

- name: reapply ip6tables
  service: name=ip6tables state=reloaded
